Controllers/ExcelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.IO;
using ClosedXML.Excel;

namespace ResultDataMining.Controllers
{
    public class ExcelController : Controller
    {
        // GET: Excel
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UploadExcel()
        {
            return View();
        }

        public ActionResult GetExcel()
        {
            DataTable dt = (DataTable)Session["ExamTable"];
            return View(dt);
        }



        [HttpPost]
        public ActionResult UploadExcel(HttpPostedFileBase file)
        {
            DataTable dt = new DataTable();
            //Checking file content length and Extension must be .xlsx
            if (file != null && file.ContentLength > 0 && System.IO.Path.GetExtension(file.FileName).ToLower() == ".xlsx")
            {
                string path = Path.Combine(Server.MapPath("~/UploadFile"), Path.GetFileName(file.FileName));
                //Saving the file
                file.SaveAs(path);
                //Started reading the Excel file.
                using (XLWorkbook workbook = new XLWorkbook(path))
                {
                    IXLWorksheet worksheet = workbook.Worksheet(1);
                    bool FirstRow = true;
                    //Range for reading the cells based on the last cell used.
                    string readRange = "1:1";
                    foreach (IXLRow row in worksheet.RowsUsed())
                    {
                        //If Reading the First Row (used) then add them as column name
                        if (FirstRow)
                        {
                            //Checking the Last cellused for column generation in datatable
                            readRange = string.Format("{0}:{1}", 1, row.LastCellUsed().Address.ColumnNumber);
                            foreach (IXLCell cell in row.Cells(readRange))
                            {
                                dt.Columns.Add(cell.Value.ToString());
                            }
                            FirstRow = false;
                        }
                        else
                        {
                            //Adding a Row in datatable
                            dt.Rows.Add();
                            int cellIndex = 0;
                            //Updating the values of datatable
                            foreach (IXLCell cell in row.Cells(readRange))
                            {
                                dt.Rows[dt.Rows.Count - 1][cellIndex] = cell.Value.ToString();
                                cellIndex++;
                            }
                        }
                    }
                    //If no data in Excel file
                    if (FirstRow)
                    {
                        ViewBag.Message = "Empty Excel File!";
                    }
                    Session.Add("ExamTable", dt);
                }
            }
            else
            {
                //If file extension of the uploaded file is different then .xlsx
                ViewBag.Message = "Please select file with .xlsx extension!";
            }
            return View(dt);
        }
    }
}

Controllers/GraphController.cs
using ClassLibrary;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ResultDataMining.Controllers
{
    public class GraphController : Controller
    {
        // GET: Graph
        public ActionResult Index()
        {
            return View();
        }



        public object ConvertJSON()
        {
            DataTable dt = (DataTable)Session["ExamTable"];
            ATTConvert obj = new ATTConvert();             
            return obj.DataTableToJSONWithJSONNet(dt);
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ResultDataMining.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Excel/GetExcel.cshtml
@{
    ViewBag.Title = "GetExcel";
}

<h2>GetExcel</h2>

@using System.Data
@model DataTable
@{
    //Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ReadExcelFile</title>
    <style>
        table {
            border: 1px solid #000000;
            text-align: left;
            border-collapse: collapse;
            margin-top: 20px;
        }

            table td, table th {
                border: 1px solid #000000;
                padding: 5px 4px;
            }

            table th {
                background-color: #5396d2;
                color: white;
            }
    </style>
</head>
<body>

    @using (Html.BeginForm("GetExcel", "Excel", FormMethod.Get, new { enctype = "multipart/form-data" }))
    {

        if (Model != null)
        {

            <table>
                <tr>
                    @for (int i = 0; i < Model.Columns.Count; i++)
                    {
                        <th>@Model.Columns[i].ColumnName</th>
                    }
                </tr>
                @for (int i = 0; i < Model.Rows.Count; i++)
                {
                    <tr>
                        @for (int j = 0; j < Model.Columns.Count; j++)
                        {
                            <td>@Model.Rows[i][j]</td>
                        }
                    </tr>
                }
            </table>
        }

        <div>

        </div>
    }
</body>
</html>

Views/Excel/UploadExcel.cshtml
@{
    ViewBag.Title = "UploadExcel";
}

<h2>UploadExcel</h2>

@using System.Data
@model DataTable
@{
    //Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ReadExcelFile</title>
    <style>
        table {
            border: 1px solid #000000;
            text-align: left;
            border-collapse: collapse;
            margin-top: 20px;
        }

            table td, table th {
                border: 1px solid #000000;
                padding: 5px 4px;
            }

            table th {
                background-color: #5396d2;
                color: white;
            }
    </style>
</head>
<body>
    @using (Html.BeginForm("UploadExcel", "Excel", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="row">
            <div class="col-md-3">
                <label>Upload File:</label>
            </div>
            <div class="col-md-3">
                <input class="btn-primary" type="file" id="file" name="file" />
            </div>
            <div class="col-md-2">
                <input type="submit" value="Upload File">
            </div>
        </div>

        <!--Display Error Message-->
        <div style="color:red;">@ViewBag.Message</div>
        <!--Show the Data Table on the View after reading the Excel File-->
        if (Model != null)
        {

            <table>
                <tr>
                    @for (int i = 0; i < Model.Columns.Count; i++)
                    {
                        <th>@Model.Columns[i].ColumnName</th>
                    }
                </tr>
                @for (int i = 0; i < Model.Rows.Count; i++)
                {
                    <tr>
                        @for (int j = 0; j < Model.Columns.Count; j++)
                        {
                            <td>@Model.Rows[i][j]</td>
                        }
                    </tr>
                }
            </table>
        }
        <div>

        </div>
    }

  

    @*@Html.ActionLink("Go to Graph", "Index", "Graph")*@
</body>
</html>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
  

</script>

Views/Graph/ConvertJSON.cshtml
@{
    ViewBag.Title = "ConvertJSON";
}

<h2>ConvertJSON</h2>

Views/Graph/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>

<!DOCTYPE HTML>
<html>
<head>
    <script>
      
    </script>
</head>
<body>
    <br />
    <div class="row">
        <div class="col-md-2">
            <b>Graph Type</b>
        </div>

        <div class="col-md-4">
            <select id="ddlReportType" class="form-control" data-bind="options: ReportTypes , optionsText:'ReportType', optionsValue:'Id', optionsCaption: '------SELECT------',value:SelectedReportType, event : {change : ChangeGraphType }"></select>
        </div>


        <div class="col-md-2">
            <b>Batch</b>
        </div>
        <div class="col-md-4">
            <select id="ddlBatch" class="form-control"
                    data-bind="options:Batchs, optionsText:'Batch', optionsValue:'Batch', optionsCaption: '------SELECT------',value:SelectedBatch, event : { change :  ChangeBatch }"></select>
        </div>
    </div>

    <br />
    <div class="row">

        <div class="col-md-2">
            <b>Faculty</b>
        </div>

        <div class="col-md-4">



            <select id="ddlFaculty" class="form-control"
                    data-bind="options:Faculties, optionsText:'Faculty', optionsValue:'Faculty', optionsCaption: '------SELECT------',value:SelectedFaculty, event : { change : ChangeFaculty} "></select>
        </div>

        <div class="col-md-2">
            <b>Category</b>
        </div>


        <div class="col-md-4">
            <select id="ddlBatch" class="form-control"
                    data-bind="options:Categories, optionsText:'Cat', optionsValue:'Cat', optionsCaption: '------SELECT------',value:SelectedCat, event : { change : ChangeCat } "></select>
        </div>

    </div>

    <br />
    <div class="row" id="divRoll">


        <div class="col-md-2">
            <b>Gender</b>
        </div>

        <div class="col-md-4">

            <select id="ddlSem" class="form-control"
                    data-bind="options:Genders, optionsText:'Gender', optionsValue:'Gender', optionsCaption: '------SELECT------',value:SelectedGender, event: {change : ChangeGender}"></select>
        </div>


        <div class="col-md-2">
            <b>Rank</b>
        </div>

        <div class="col-md-4">

            <select id="ddlSem" class="form-control"
                    data-bind="options:Ranks, optionsText:'Rank', optionsValue:'Rank', optionsCaption: '------SELECT------',value:SelectedRank"></select>
        </div>


    </div>
    <br />

    <div class="row" id="divSemester">

        <div class="col-md-2">
            <b>Semester</b>
        </div>

        <div class="col-md-4">

            <select id="ddlSem" class="form-control"
                    data-bind="options:Semesters, optionsText:'Sem', optionsValue:'Sem', optionsCaption: '------SELECT------',value:SelectedSem"></select>
        </div>

        <div id="divSem2">
            <div class="col-md-2">
                <b>Semester</b>
            </div>

            <div class="col-md-4">

                <select class="form-control"
                        data-bind="options:Semesters, optionsText:'Sem', optionsValue:'Sem', optionsCaption: '------SELECT------',value:SelectedSem2"></select>
            </div>
        </div>
    </div>

    <br />




    <div class="row">
        <button type="button" class="btn-primary" data-bind="click: Search"> Search</button>
        <button type="button" class="btn-primary" data-bind="click: Reset"> Reset</button>

    </div>


    <center><div id="chartContainer" style="height: 350px; width: 50%;"></div>  </center>
    <div id="chartContainer1" style="height: 450px; width: 100%;"></div>
    <button id="exportChart1" class="btn-primary">Export Chart</button>
    <div id="chartContainer2" style="height: 450px; width: 100%;"></div>
    <button id="exportChart2" class="btn-primary">Export Chart</button>
    <div id="chartContainer3" style="height: 450px; width: 100%;"></div>
    <button id="exportChart3" class="btn-primary">Export Chart</button>
    <div id="chartContainer4" style="height: 850px; width: 100%;"></div>
    <button id="exportChart4" class="btn-primary">Export Chart</button>
    <div id="chartContainer5" style="height: 850px; width: 100%;"></div>
    <button id="exportChart5" class="btn-primary">Export Chart</button>
    <div id="chartContainer6" style="height: 850px; width: 100%;"></div>
    <button id="exportChart6" class="btn-primary">Export Chart</button>


    <br />
    <br />


    <script src="~/Scripts/canvasjs.min.js"></script>
</body>
</html>

<script src="~/Scripts/knockout-3.5.0.js"></script>
<script src="~/Scripts/ResultData/Graph.js"></script>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Exam Result Analytics</h1>
    <p class="lead">Exam Result Analytics is a software for observing overall performance pattern of IOE Students</p>
  
</div>

<div class="row">
    <div class="col-md-4">
     
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Exam Data Mining</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Exam Data Mining", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Graph", "Index", "Graph")</li>
                    <li>@Html.ActionLink("Upload Excel", "UploadExcel", "Excel")</li>
                    <li>@Html.ActionLink("Get Excel", "GetExcel", "Excel")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Exam Data Mining Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>


<link href="~/Content/bootstrap.min.css" rel="stylesheet" />


<link href="~/Content/jquery-confirm.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-confirm.min.js"></script>